### ISSUE TITLE
Assetic configuration

### ISSUE THREAD

**Issue by auchalet** [lokhman/silex-assetic#1]
Hello !

I try to install your Assetic integration for Silex.

When I launch assetic:dump command, there are no errors, but no files are dumping.

Here the output of the command :
```
> php bin/console assetic:dump
Dumping all assets to /path_to_my_project/web.
Debug mode is on.
```

Here you can see how I configure Assetic for dumping AdminLTE less files located in vendors, following your documentation and Assetic's :
```
$app->register(new \Lokhman\Silex\Provider\AsseticServiceProvider(), array(

    'assetic.options' => array(
        'prefix' => '/',
        'input_dir' => 'src/Resources/less',
        'output_dir' => 'web',
        'cache_dir' => 'var/cache/assetic',
        'node' => '/usr/bin/node',

        'filters' => array(
            'sass' => array(
                'bin' => '/usr/local/bin/sass'
            ),
            'less' => array(
                'bin' => '/usr/bin/less'
            )
        ),

        // Liste des assets à compiler
        'assets' => array(

            'backend_css' => array(
                'inputs' => array(
                    '../vendor/almasaeed2010/adminlte/build/less/AdminLTE.less',
                    '../vendor/almasaeed2010/adminlte/build/less/skins/_all-skins.less'
                ),
                'filters' => array(
                    'less'
                ),
                'output' => array(
                    'css/backend/style.css'
                )
            )
        )

    )

));
```

Here you can see my exec console file : 

```
#!/usr/bin/env php
<?php

require __DIR__ . '/../vendor/autoload.php';

use Silex\Application;
use Silex\Provider as Providers;
use Lokhman\Silex\Console\Console;
use Lokhman\Silex\Console\Command as Commands;

$app = new Application();

// On récupère les services qu'on a déjà register
require __DIR__ . '/../app/config/dev.php';
require __DIR__ . '/../app/config/assetic.php';


// Création d'un objet Console
$console = new Console($app);

// Ajout de la commande pour dump les assets
$console->add(new Commands\Assetic\DumpCommand());

$console->run();
```

Have you got an idea for how debug this ? Or an example of the provider configuration maybe ? 

Thanks a lot for your help :)

**Comment by lokhman** [comment]
Hi! Thank you for the first issue here :)

From what I see, you defined `"output"` property for `backend_css` asset, which doesn't do anything, as output path cannot be specified here. Assets defined in `assets` options property can be used, for example, in templates. In Twig you can define `output` option with:

```
{% stylesheets '@backend_css' output='styles.css' %}
    <link rel="stylesheet" href="{{ asset_url }}" />
{% endstylesheets %}
```

Then, when you will run dump command, script will find all usages of your assets and dump them to the output path.

It's also worth noting that you may use `--no-debug` option for dump command, which will dump assets as you would do it in production.

**Comment by auchalet** [comment]
Thanks for your quick reply and tips :)

Indeed, I didn't saw that this option didn't exist ^^
Then, I put your code in my layout.html.twig and I refresh the page. 
Good point : assets are being well compiled in var/cache/assetic and well load in my layout :smile: 

However, the styles are not compiled in my output folder (in `web/css`), neither during the page load or when typing the `assetic:dump` command (with or without `--no-debug` option).

Another little question : Can I declare paths "like Symfony" with `%kernel.root_dir%` or something else ?
I tried to add some $app globals but I can't access it in Assetic configuration :/

**Comment by auchalet** [comment]
I found that the Twig Extension needed to be loaded for real dumping files.
After added it, it works like a charm :+1: 

Thanks for your help :)
