### ISSUE TITLE
Dump Font files 

### ISSUE THREAD

**Issue by auchalet** [lokhman/silex-assetic#2]
Hi again ! :p 

This time, I would like to load Font-awesome that I downloaded by Composer.
I successfully dump the css located in vendors, but it needs to load some font files (otf, eot, ttf, ...)

I looked for an Assetic solution and I found this link : 
http://stackoverflow.com/questions/23443773/symfony2-assetic-css-font-icons

But, like you told me in #1, the output option in assets block do nothing.
Have you got an idea for loading them ?

Thanks ! :)

**Comment by lokhman** [comment]
Hi! Sorry for not replying for long time.

From what I understand, Assetic doesn't copy dependency files to your `web` folder, as it cannot identify the actual dependencies and how they should be included to other assets. Instead you need to keep all these files in `web` folder and, as an example, use `cssrewrite` filter to fix the relative paths.

But beware, in debug mode `silex-assetic` library works in the same way, as it works in Symfony -- it doesn't generate actual files, but creates virtual routes, so your framework can resolve them.

**Comment by lokhman** [comment]
Also, I'm glad that you've resolved the issue #1, and answering your question about configuration:

> Another little question : Can I declare paths "like Symfony" with %kernel.root_dir% or something else ?
I tried to add some $app globals but I can't access it in Assetic configuration :/

I'd suggest you to use [`silex-config`](https://github.com/lokhman/silex-config) library, it integrates perfectly well with Silex setup and can support lots of nice features you may like to use :)

**Comment by auchalet** [comment]
Hi !
I resolve this by installing Font-Awesome with Bower in web directory.
Then I can access CSS with `{{ asset() }}` and fonts are well loaded 😃 

Thanks for your library, but I found another solution by installing https://github.com/m1/Vars, and it works perfectly 👍 

I can close this issue, thanks for your help ! 😃

**Comment by lokhman** [comment]
Great, that you've resolved all your issues.

Vars is a good library but it is quite heavy for Silex, as a fast micro-framework. If you will ever require really lightweight solution for managing configuration, I'd recommend `silex-config`.
